### ISSUE TITLE
base is not loading properly

### ISSUE THREAD

**Issue by wil2005-development** [Im-Sam/Pixelworld#1]
Hey,

I have this server download from your github unfortunately I run into a problem right away:
1. There is no SQL file
2. pw_base does not load.

There is no sql file so I don't have a good database so I hope you still have it and pw_base doesn't load properly it goes through steps 1 and 2 well but then we have to get to step 3 unfortunately it doesn't even get there so I have the read through the code apparently it should get started = true so I'm looking for that that should be exported but that doesn't even happen. so pw_base would also load. I would like to hear from you a fix so that I can use this

**Comment by Im-Sam** [comment]
Hello,

As the readme states, this was a test project that I have moved on from. Server started and ran on my machine when these files were uploaded and there were no issues around pw_base (however there were some bug in the server).

I do not have the original SQL file but I have attached the file from another version of this that _may_ work for you: 
[database-starter.txt](https://github.com/Im-Sam/Pixelworld/files/7567276/database-starter.txt)

If this doesn't work, the database can be made manually, _relatively easily_ from reading the scripts.

Best of luck.
